name = "CodeEdit"
uuid = "ef324658-459a-46c1-a175-ab8d0771bbcc"
authors = ["Per Rutquist <per.rutquist@gmail.com> and contributors"]
version = "0.1.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
